version: v7
n_params: 2916
environment:
  name: FrozenLake-v1
  input_shape: 16
  n_actions: 4
training:
  n_iter: 22285
  mean_default_bound: 4.7
  gamma: 0.99
  replay_buffer_size: 10000
  replay_buffer_start_size: 10000
  batch_size: 32
  learning_rate: 0.0001
  sync_target_frames: 1000
  epsilon_decay_last_frame: 20000
  epsilon_decay_start: 1.0
  epsilon_decay_final: 0.01
