version: v8
n_params: 71172
environment:
  name: FrozenLake-v1
  input_shape: 16
  n_actions: 4
training:
  n_iter: 53018
  mean_default_bound: 4.7
  gamma: 0.95
  replay_buffer_size: 50000
  replay_buffer_start_size: 50000
  batch_size: 64
  learning_rate: 0.0001
  sync_target_frames: 10
  epsilon_decay_last_frame: 20000
  epsilon_decay_start: 1.0
  epsilon_decay_final: 0.01
